#server:
#  port: 9899
#spring:
#  application:
#    name: LaptopFilter_Jpastreamer_Application
#  datasource:
#    url: jdbc:mysql://localhost:3306/laptopdatabase;
#    username: root
#    password: pass
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true